### ISSUE TITLE
feed-gipeda does not react to a changed gipeda.yaml

### ISSUE THREAD

**Issue by nomeata** [sgraf812/feed-gipeda#12]
After changing the benchmarkScript in a repository, it seems that feed-gipeda still uses the previous one. Also other settings from `gipeda.yaml` in the repository are ignored.

Of course this needs some thought. Which `gipeda.yaml` should be used for checking a specific commit – always `master`, or always the one from the commit in question. Not easy...

**Comment by sgraf812** [comment]
That's strange. I decided to always use the most recent commit's gipeda.yaml. I'll look into it.

I think using the most recent commit is the only viable solution here.

**Comment by nomeata** [comment]
> I think using the most recent commit is the only viable solution here.

A problem could be if the `benchmarkSkript` refers to a file in the repository, then it may not be present in older versions. But we can leave that complexity to the user for now.

**Comment by sgraf812** [comment]
> After changing the benchmarkScript in a repository, it seems that feed-gipeda still uses the previous one.

I _think_ I fixed that, but haven't really something to reproduce it anymore.

**Comment by nomeata** [comment]
Yes, seems to be fixed.
